### ISSUE TITLE
I would like to submit a fork.

### ISSUE THREAD

**Issue by MrCodeInc** [hako/googol-glados-simulator#16]
Hi hako I don't mean to annoy you but i made ggs that allows mobile viewing but I don't know how to host it. Here's a link to code and please tell me how to host it if like it. Link:https://github.com/MrCodeInc/ggsmobile

**Comment by hako** [comment]
@MrCodeInc I advise you to test your changes on your computer before you add code to this simulator. I can host your changes, but I need to know if your code works first. You need a terminal and Node.js to do this: 

[Install Node.js on Windows](http://blog.teamtreehouse.com/install-node-js-npm-windows)
[Install Node.js on Mac](http://blog.teamtreehouse.com/install-node-js-npm-mac)

Once you've installed Node.js, [Install Bower](https://bower.io/#install-bower).

You can then download the Simulator and type in the terminal `npm install; bower install`

Start the Googol GLaDOS Simulator by typing `node app.js` and then you can view the app in a browser. You can then edit the code and then view those changes in the browser.

If you want to host your own version of the simulator, signup to [Heroku](https://heroku.com). I advise reading [Getting Started on Heroku with Node.js](https://devcenter.heroku.com/articles/getting-started-with-nodejs#introduction) first.

**Comment by hako** [comment]
@MrCodeInc As for your fork: There is still a lot of work here for the Googol GLaDOS Simulator to work on mobile. (Which is why I disabled it for mobile users.) 

You are free to work on it but it needs a lot more changes to work properly on mobile.

**Comment by MrCodeInc** [comment]
@hako ok i will work harder on it will talk later. thanks. :D

**Comment by MrCodeInc** [comment]
@hako any ideas on how to make this simulator run on mobile

**Comment by MrCodeInc** [comment]
@hako also my fork is not to made to make it work on mobile it was made for people who want to see it on mobile any way.

**Comment by hako** [comment]
@MrCodeInc But it's going to take more than a simple change to make it work on mobile. In fact even if you change the button on the page and press the launch button, it still blocks you because the simulator detects you are on a mobile device. And I don't intend to change this unless the following are fixed on mobile:
- The UI
- Audio
- Graphics resizing

Even if you let people view it on mobile with no restrictions, if the above don't work, viewers are going to have a bad experience using the simulator if there is no audio playing on the device, the UI is cumbersome and the graphics are out of place on the webpage.

**Comment by MrCodeInc** [comment]
@hako Ok. also I'm able to request the desktop site on chrome on mobile.

**Comment by MrCodeInc** [comment]
@hako also I want my site to detect mobile user and redirect to the mobile site could you help me and give me the code?

**Comment by MrCodeInc** [comment]
@hako P.S. i fixed app.js to not detect Mobile....I think.

**Comment by MrCodeInc** [comment]
@hako I deployed it to heroku and it says Internal Server Error and do know why please help link is [here](https://ggsmobile.herokuapp.com/)

**Comment by hako** [comment]
@MrCodeInc [Check the server logs](https://devcenter.heroku.com/articles/logging#view-logs).

**Comment by MrCodeInc** [comment]
@hako I don't know much about heroku because i just signed up for it and I am new could you please help and explain that and don't think I am noon in coding I just don't know how to work heroku.

**Comment by MrCodeInc** [comment]
@hako I don't know much about heroku because i just signed up for it and I am new could you please help and explain that and don't think I am noob in coding I just don't know how to work heroku.

**Comment by hako** [comment]
@MrCodeInc Did you read the tutorial on [Getting Started on Heroku with Node.js](https://devcenter.heroku.com/articles/getting-started-with-nodejs#introduction)?

**Comment by MrCodeInc** [comment]
@hako no but I gonna now.

**Comment by MrCodeInc** [comment]
@hako now I did.

**Comment by MrCodeInc** [comment]
Also when you were talking about logs did you mean application logs. If so the app logs are:
2016-08-08T22:53:35.445301+00:00 app[web.1]:     at Route.dispatch (/app/node_modules/express/lib/router/route.js:112:3)
2016-08-08T22:53:35.445300+00:00 app[web.1]:     at Layer.handle [as handle_request](/app/node_modules/express/lib/router/layer.js:95:5)
2016-08-08T22:53:35.445305+00:00 app[web.1]:     at logger (/app/node_modules/morgan/index.js:144:5)
2016-08-08T22:53:35.445304+00:00 app[web.1]:     at Function.process_params (/app/node_modules/express/lib/router/index.js:330:12)
2016-08-08T22:53:35.445299+00:00 app[web.1]:     at /app/app.js:101:17

**Comment by MrCodeInc** [comment]
@hako I added you as a collaborator on heroku so if you want to help you can.

**Comment by hako** [comment]
@MrCodeInc Email? I don't think I received your collaborator request.

**Comment by MrCodeInc** [comment]
@hako  will send a request again Also did u check your email?

**Comment by hako** [comment]
@MrCodeInc I've already solved it, your app is now running.

**Comment by MrCodeInc** [comment]
@hako Thanks Soooo Much :D

**Comment by MrCodeInc** [comment]
@hako am I on the list of mirrors and forks on the site?!?!?!?

**Comment by hako** [comment]
I have closed this issue until further changes have been made on your fork. Implement the following [here](https://github.com/hako/googol-glados-simulator/issues/16#issuecomment-236552549) then open a pull request.
